IF OBJECT_ID('dbo.Sales') IS NULL
BEGIN 
	CREATE TABLE [dbo].[Sales]
	(
		[Id] INT NOT NULL
	)
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.objects WHERE name = 'pk_SalesID' AND type = 'PK')
ALTER TABLE [dbo].[Sales]
WITH CHECK ADD CONSTRAINT pk_SalesID PRIMARY KEY CLUSTERED (
		Id ASC)
GO